### ISSUE TITLE
TypeError: nightmare.goto(...).clickByXpath(...).wait is not a function

### ISSUE THREAD

**Issue by brw31415** [yonaichin/nightmare-xpath-event#1]
the nightmare.js   .wait() seems to not work when it is preceeded by  .clickByXpath(...)

the error is at line 40 in the code is here :  https://pastebin.com/bMZmYef9

**Comment by yonaichin** [comment]
Hi
The library is required the wrong way.
Check the code down below if you're using ES5
```
var Nightmare = require('nightmare');
var nightmare = Nightmare({ show: true });
 
var NXE = require('nightmare-xpath-event');
 
Nightmare.action('touch', NXE.touch)
Nightmare.action('clickByXpath', NXE.clickByXpath)
 
```

let me know if there's still any problems
